### ISSUE TITLE
consider removing dependency on sinatra-contrib

### ISSUE THREAD

**Issue by samandmoore** [Betterment/webvalve#5]
we're only using it for json support, and that's really only a 3 line method.

**Comment by preetsethi** [comment]
Wanted to say thank you for your work first. Since you're considering this, wanted to propose an argument against. Including sinatra-contrib lets me do this
```ruby
require 'sinatra/namespace'

class FakeExample < WebValve::FakeService
  register Sinatra::Namespace

  namespace '/api' do
    namespace '/v3' do

      namespace '/top_level_abstraction_1' do
        get '/endpoint1.json' do
          json result: 'it works!'
        end
        get '/endpoint2.json' do
          json result: 'it works!'
        end
      end

      namespace '/top_level_abstraction_2' do
        get '/endpoint1.json' do
          json result: 'it works!'
        end
        get '/endpoint2.json' do
          json result: 'it works!'
        end
      end

    end
  end
end
```
My application integrates with many services, and a common API pattern is organizing by grouping into top level abstractions. Namespacing helps to keep things organized, and actually ends up being a great jump off point to document which API calls my application supports.

Just one argument; once again thanks for your work!

**Comment by samandmoore** [comment]
not doing it. it seems nice to have the helpers for sinatra available.
